name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          config_timezone: Asia/Shanghai
#          config_display: columns  # отображать информацию по колонкам
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata  # базовый контент (информация о пользователе)
          plugin_introduction: yes  # общая информация о аккаунте
#          plugin_sponsors: yes

          plugin_isocalendar: yes  # 3д изокалендарь
          plugin_isocalendar_duration: full-year  # отображает активность за полный год

          plugin_languages: yes  # отображение применяемых языков программирования
          plugin_languages_details: bytes-size, percentage  # дополнительная информация о коде размер и процент

          plugin_achievements: yes
          plugin_achievements_threshold: X  # (покажет фишки достижений которые еще не разблокированы)
          plugin_achievements_display: detailed  # детальное описание фишек достижений
          plugin_achievements_ignored: projects-classic

          plugin_calendar: yes  # отображает активность по годам от текущего и далее
          plugin_calendar_limit: 11 # отображает активность за столько лет

          plugin_habits: yes  # активность за сутки и неделю
          plugin_habits_facts: yes  # отображает анализ вашей активность за неделю
          plugin_habits_charts: yes  # отображает характеристики
          plugin_habits_trim: yes

          plugin_lines: yes
          plugin_lines_delay: 1
          plugin_lines_sections: base
          plugin_lines_skipped: none

          plugin_skyline: yes  # плагин 3д активности скайлайн
          plugin_skyline_year: 2025 # за какой год
          plugin_skyline_frames: 60  # количество кадров
          plugin_skyline_quality: 0  # качество 1 - лучшее

          plugin_stargazers: yes  # активность за месяц
          plugin_stargazers_charts_type: graph  # тип активности - плавные линии

          plugin_activity: yes
          plugin_activity_limit: 5

          plugin_gists: yes

          plugin_contributors: yes
          plugin_stars: yes
          plugin_traffic: yes

          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_types: pr, issue

          plugin_people: yes
          plugin_people_limit: 10

          plugin_reactions: yes
          plugin_reactions_limit: 10

          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_discussions_categories_limit: 8

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_code: yes
          plugin_code_lines: 4
          plugin_code_visibility: public

          plugin_starlists: yes
          plugin_starlists_limit: 10
          plugin_starlists_languages: yes

          plugin_sponsors: yes

          plugin_repositories: yes
          plugin_repositories_featured: yes
          plugin_repositories_pinned: yes

          plugin_topics: yes  # плагин ипсользуемых тем
          plugin_topics_limit: 0
          plugin_topics_mode: icons